---

- hosts: localhost

  become: yes



  tasks:

    - name: Create VPC

      ec2_vpc_net:

        name: Test VPC

        cidr_block: 10.1.0.0/24

        region: ap-northeast-2

        state: present

      register: vpc_result

